// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/24/2025, 10:07:28 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/sac/cns/aegis-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sac/cns/aegis-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sac/cns/aegis-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sac/cns/aegis-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sac/cns/aegis-nuxt/plugins/**/*.{js,ts,mjs}","/Users/sac/cns/aegis-nuxt/composables/**/*.{js,ts,mjs}","/Users/sac/cns/aegis-nuxt/utils/**/*.{js,ts,mjs}","/Users/sac/cns/aegis-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sac/cns/aegis-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sac/cns/aegis-nuxt/app.config.{js,ts,mjs}"]}},
{"content":["~/components/**/*.{vue,js,ts}","~/layouts/**/*.vue","~/pages/**/*.vue","~/plugins/**/*.{js,ts}","~/app.vue"],"theme":{"extend":{"colors":{"cyber-blue":"#00d4ff","cyber-green":"#00ff88","cyber-red":"#ff0040","cyber-yellow":"#ffaa00","cyber-purple":"#aa00ff","cyber-gray":"#1a1a1a","cyber-dark":"#0a0a0a"},"animation":{"pulse-slow":"pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite","glow":"glow 2s ease-in-out infinite alternate"},"keyframes":{"glow":{"0%":{"boxShadow":"0 0 5px #00d4ff"},"100%":{"boxShadow":"0 0 20px #00d4ff, 0 0 30px #00d4ff"}}}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;