apiVersion: apps/v1
kind: Deployment
metadata:
  name: cns-forge-8020
  namespace: cns-system
  labels:
    app: cns-forge-8020
    version: "8020"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cns-forge-8020
  template:
    metadata:
      labels:
        app: cns-forge-8020
        version: "8020"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: cns-forge-8020
        image: cns-forge:8020
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        - containerPort: 8081
          name: health
        env:
        - name: CNS_FORGE_TTL_HOPS
          value: "8"
        - name: CNS_FORGE_TICK_BUDGET
          value: "8"
        - name: CNS_FORGE_TELEMETRY_ENABLED
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cns-forge-8020-service
  namespace: cns-system
  labels:
    app: cns-forge-8020
spec:
  selector:
    app: cns-forge-8020
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 9090
  - name: health
    port: 8081
    targetPort: 8081
  type: ClusterIP
