apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitactor.fullname" . }}-config
  labels:
    {{- include "bitactor.labels" . | nindent 4 }}
data:
  bitactor.yaml: |
    server:
      port: {{ .Values.service.port }}
      metrics_enabled: true
      tick_budget: {{ .Values.bitactor.performance.tickBudget }}
      ring_size: {{ .Values.bitactor.performance.ringSize }}
    
    performance:
      thread_count: {{ .Values.bitactor.performance.threadCount }}
      batch_size: {{ .Values.bitactor.performance.batchSize }}
      priority_levels:
        {{- toYaml .Values.bitactor.signalProcessing.priorityLevels | nindent 8 }}
    
    security:
      enable_tls: {{ .Values.bitactor.security.enableTLS }}
      atomic_operations: {{ .Values.bitactor.security.atomicOperations }}
      endianness_check: {{ .Values.bitactor.security.endiannessCheck }}
    
    signal_processing:
      max_signals_per_second: {{ .Values.bitactor.signalProcessing.maxSignalsPerSecond }}
      max_latency_micros: {{ .Values.bitactor.signalProcessing.maxLatencyMicros }}
    
    monitoring:
      prometheus_enabled: {{ .Values.monitoring.prometheus.enabled }}
      metrics_port: {{ .Values.service.port }}