
apiVersion: v1
kind: Namespace
metadata:
  name: testvalidationab6bb92e
  labels:
    app: testvalidationab6bb92e
    workflow-type: cybersecurity_mesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testvalidationab6bb92e-reactor
  namespace: testvalidationab6bb92e
  labels:
    app: testvalidationab6bb92e
    component: reactor-workflow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testvalidationab6bb92e
      component: reactor-workflow
  template:
    metadata:
      labels:
        app: testvalidationab6bb92e
        component: reactor-workflow
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: reactor-workflow
        image: testvalidationab6bb92e/reactor:latest
        ports:
        - containerPort: 4000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: WORKFLOW_TYPE
          value: "cybersecurity_mesh"
        - name: BITACTOR_INTEGRATION
          value: "true"
        - name: PERFORMANCE_MODE
          value: "optimized"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: testvalidationab6bb92e-service
  namespace: testvalidationab6bb92e
spec:
  selector:
    app: testvalidationab6bb92e
    component: reactor-workflow
  ports:
  - name: http
    port: 80
    targetPort: 4000
  - name: metrics
    port: 9090
    targetPort: 9090
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: testvalidationab6bb92e-metrics
  namespace: testvalidationab6bb92e
spec:
  selector:
    matchLabels:
      app: testvalidationab6bb92e
  endpoints:
  - port: metrics
    interval: 15s
