name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [cns_litigator, cns_quant, cns_clinician, cns_fabricator]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make python3-pip
        pip3 install -r requirements.txt
    
    - name: Build service
      run: |
        cd generated/${{ matrix.service }}
        make
    
    - name: Run tests
      run: |
        cd generated/${{ matrix.service }}
        python test_${{ matrix.service }}.py
    
    - name: Performance benchmark
      run: |
        cd generated/${{ matrix.service }}
        ./benchmark_8tick || true
    
    - name: Security scan
      run: |
        # Run security scanning
        echo "Security scan for ${{ matrix.service }}"
  
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push Docker images
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        for service in cns_litigator cns_quant cns_clinician cns_fabricator; do
          docker build -t $DOCKER_REGISTRY/${service}:${{ github.sha }} generated/${service}
          docker push $DOCKER_REGISTRY/${service}:${{ github.sha }}
        done
