
apiVersion: v1
kind: ConfigMap
metadata:
  name: cns-forge-health-checks
  namespace: cns-forge
data:
  health-check.sh: |
    #!/bin/bash
    # CNS Forge Health Check Script
    curl -f http://localhost:8080/health || exit 1
    curl -f http://localhost:9090/metrics || exit 1
    
  monitoring.yaml: |
    healthCheck:
      interval: 5s
      timeout: 10s
      retries: 3
      endpoints:
        - path: /health
          port: 8080
        - path: /metrics
          port: 9090
