# OAuth2 Configuration
oauth2:
  providers:
    - name: google
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      redirect_uri: https://api.cns-forge.io/auth/google/callback
      scopes:
        - openid
        - profile
        - email
    
    - name: github
      client_id: ${GITHUB_CLIENT_ID}
      client_secret: ${GITHUB_CLIENT_SECRET}
      redirect_uri: https://api.cns-forge.io/auth/github/callback
      scopes:
        - user:email
        - read:user

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600
  refresh_expiration: 86400
