apiVersion: v1
kind: Namespace
metadata:
  name: cns-forge
  labels:
    name: cns-forge
    environment: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cns-forge-sa
  namespace: cns-forge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cns-forge-role
  namespace: cns-forge
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cns-forge-rolebinding
  namespace: cns-forge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cns-forge-role
subjects:
- kind: ServiceAccount
  name: cns-forge-sa
  namespace: cns-forge
