apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-bitactor
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-bitactor
  template:
    metadata:
      labels:
        app: jaeger-bitactor
    spec:
      containers:
      - env:
        - name: COLLECTOR_OTLP_ENABLED
          value: 'true'
        image: jaegertracing/all-in-one:latest
        name: jaeger
        ports:
        - containerPort: 16686
        - containerPort: 14250
