global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
- job_name: bitactor-pipeline
  kubernetes_sd_configs:
  - namespaces:
      names:
      - bitactor-system
    role: pod
  relabel_configs:
  - action: keep
    regex: 'true'
    source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_scrape
- job_name: otel-collector
  static_configs:
  - targets:
    - otel-collector:8889
