apiVersion: v1
kind: Namespace
metadata:
  name: cns-system
  labels:
    app: cns
    environment: production
    security: enabled
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cns-resource-quota
  namespace: cns-system
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    pods: "50"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cns-limit-range
  namespace: cns-system
spec:
  limits:
  - max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: 500m
      memory: 512Mi
    type: Container
  - max:
      cpu: "4"
      memory: 4Gi
    min:
      cpu: 200m
      memory: 256Mi
    type: Pod