apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  namespace: e2e-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-service
  template:
    metadata:
      labels:
        app: test-service
    spec:
      containers:
      - name: test-service
        image: test-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: e2e-test
spec:
  selector:
    app: test-service
  ports:
  - port: 80
    targetPort: 8080