{application,bitactor,
             [{description,"BitActor - Production Financial Computing Engine"},
              {vsn,"1.0.0"},
              {registered,[bitactor_sup,bitactor_server]},
              {applications,[kernel,stdlib,sasl,lager,runtime_tools]},
              {mod,{bitactor_app,[]}},
              {env,[{max_actors,10000},
                    {supervision_intensity,10},
                    {supervision_period,60},
                    {tick_interval,1000},
                    {enable_telemetry,true}]},
              {maintainers,["James I. Chatman","Sean A. Chatman"]},
              {licenses,["Proprietary"]},
              {links,[{"GitHub","https://github.com/chatmangpt/cns"}]},
              {modules,[bitactor_app,bitactor_health,bitactor_nif,
                        bitactor_pool_sup,bitactor_server,bitactor_sup,
                        bitactor_telemetry,bitactor_worker]}]}.
