{application,bitactor,
             [{description,"BitActor - Production Financial Computing Engine"},
              {vsn,"1.0.0"},
              {registered,[bitactor_sup,bitactor_server,bitactor_telemetry]},
              {applications,[kernel,stdlib,sasl,runtime_tools]},
              {mod,{bitactor_app,[]}},
              {env,[{max_actors,50000},
                    {supervision_intensity,1},
                    {supervision_period,5},
                    {tick_interval,10000},
                    {enable_telemetry,false},
                    {memory_pool_size,1000000},
                    {message_queue_limit,16384},
                    {gc_fullsweep_after,0},
                    {process_flags,[{priority,high},
                                    {min_heap_size,4096},
                                    {min_bin_vheap_size,8192},
                                    {fullsweep_after,0}]}]},
              {maintainers,["James I. Chatman","Sean A. Chatman"]},
              {licenses,["Proprietary"]},
              {links,[{"GitHub","https://github.com/chatmangpt/cns"}]},
              {modules,[bitactor_app,bitactor_benchmark,bitactor_health,
                        bitactor_nif,bitactor_pool_sup,bitactor_server,
                        bitactor_server_optimized,bitactor_sup,
                        bitactor_telemetry,bitactor_worker,
                        quick_optimization_test,quick_test,stress_runner,
                        uhft_comprehensive_test,uhft_stress_test]}]}.
